# Generated by Django 5.0.13 on 2025-03-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_code',
        ),
    ]
