# Generated by Django 5.0.13 on 2025-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collabtype_djtype_equipment_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/equipment/'),
        ),
    ]
