# Generated by Django 5.0.13 on 2025-04-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
