# Generated by Django 5.0.13 on 2025-08-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instrumenttype_instrument_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('PROFILE_COMPLETED', 'Completar perfil'), ('BRIEF_INITIATED', 'Completar briefing'), ('BRIEF_VALIDATED', 'Ver diagnóstico'), ('OBJECTIVE_SCORE_READY', 'Mejorar objetivo'), ('PLAN_SONORO_CREATED', 'Ver plan sonoro'), ('TALENT_RECOMMENDED', 'Ver recomendaciones'), ('SCOUTING_INITIATED', 'Ver scouting'), ('STRATEGY_ADJUSTMENT_REQUESTED', 'Ajustar estrategia'), ('TALENT_AVAILABILITY_CONFIRMED', 'Confirmar selección'), ('CONTINUOUS_PLAN_OFFERED', 'Agendar próximas sesiones'), ('MUSICIANS_CONFIRMED', 'Revisar scouting'), ('CONTINGENCY_PLAN_READY', 'Ver plan de respaldo'), ('PROGRESS_TRACKING_ACTIVE', 'Ver progreso'), ('EVENT_REMINDER_SENT', 'Ver detalle'), ('POST_EVENT_SURVEY_SENT', 'Enviar feedback'), ('EVENT_RESULTS_READY', 'Ver resultados'), ('BENCHMARKING_READY', 'Ver comparativa'), ('ROI_RECOMMENDATIONS_READY', 'Ver mejoras sugeridas'), ('SUBSCRIPTION_UPSELL', 'Mejorar con datos')], max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
