# Generated by Django 5.0.13 on 2025-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_read_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
