# Generated by Django 5.0.13 on 2025-09-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROFILE_COMPLETED', 'Completar perfil'), ('BRIEF_INITIATED', 'Completar briefing'), ('BRIEF_VALIDATED', 'Ver diagnóstico'), ('OBJECTIVE_SCORE_READY', 'Mejorar objetivo'), ('PLAN_SONORO_CREATED', 'Ver plan sonoro'), ('TALENT_RECOMMENDED', 'Ver recomendaciones'), ('SCOUTING_INITIATED', 'Ver scouting'), ('STRATEGY_ADJUSTMENT_REQUESTED', 'Ajustar estrategia'), ('TALENT_AVAILABILITY_CONFIRMED', 'Confirmar selección'), ('CONTINUOUS_PLAN_OFFERED', 'Agendar próximas sesiones'), ('MUSICIANS_CONFIRMED', 'Revisar scouting'), ('CONTINGENCY_PLAN_READY', 'Ver plan de respaldo'), ('PROGRESS_TRACKING_ACTIVE', 'Ver progreso'), ('EVENT_REMINDER_SENT', 'Ver detalle'), ('POST_EVENT_SURVEY_SENT', 'Enviar feedback'), ('EVENT_RESULTS_READY', 'Ver resultados'), ('BENCHMARKING_READY', 'Ver comparativa'), ('ROI_RECOMMENDATIONS_READY', 'Ver mejoras sugeridas'), ('SUBSCRIPTION_UPSELL', 'Mejorar con datos'), ('INVITE_BAND_MEMBER', 'Invitación a banda'), ('INVITE_BAND_CONFIRMED', 'Invitación a banda confirmada'), ('INVITE_BAND_DECLINED', 'Invitación a banda rechazada')], max_length=180),
        ),
    ]
