# Generated by Django 5.0.13 on 2025-10-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification_detail_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instrumenttype',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrumenttype',
            name='name',
            field=models.CharField(choices=[('musical_instruments', 'Instrumentos Musicales'), ('amplify_and_sound', 'Amplificación y Sonido'), ('illumination', 'Iluminación'), ('video_and_screens', 'Video y Pantallas'), ('scenario_and_structure', 'Escenario y Estructura'), ('energy_and_cables', 'Energía y Cables'), ('scenography', 'Escenografía'), ('production_and_logistics', 'Producción y Logística'), ('communication_and_control', 'Comunicación y Control'), ('ambiance_and_visuals', 'Ambiente y Visuales'), ('streaming_and_recording', 'Streaming y Grabación'), ('security', 'Seguridad'), ('transport_and_storage', 'Transporte y Almacenamiento')], max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instrumentcategory'),
        ),
    ]
