# Generated by Django 5.0.13 on 2025-03-21 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(choices=[('INDIVIDUAL', 'Músico Individual'), ('GROUP', 'Grupo Musical')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.attribute')),
                ('modes', models.ManyToManyField(to='services.servicemode')),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='musicians.musicproject')),
            ],
            options={
                'unique_together': {('music_project', 'attribute')},
            },
        ),
    ]
