# Generated by Django 5.0.13 on 2025-03-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_types', to='musicians.musicprojecttype'),
        ),
    ]
