# Generated by Django 5.0.13 on 2025-04-09 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_musicprojecttype_alter_musicproject_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ALBUM', 'Album'), ('EP', 'EP')], max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='discography_covers/')),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discography', to='musicians.musicproject')),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_link', models.URLField()),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles', to='musicians.musicproject')),
            ],
        ),
    ]
