# Generated by Django 5.0.13 on 2025-04-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_discography_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='availability_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='manager_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='manager_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
