# Generated by Django 5.0.13 on 2025-04-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_musicproject_availability_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discography',
            old_name='spotify_link',
            new_name='url_link',
        ),
        migrations.RenameField(
            model_name='single',
            old_name='youtube_link',
            new_name='url_link',
        ),
    ]
