# Generated by Django 5.0.13 on 2025-04-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_language'),
        ('musicians', '0005_rename_spotify_link_discography_url_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.language'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='music_genre_tags',
            field=models.ManyToManyField(blank=True, to='core.musicalgenretag'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='music_project/'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MusicProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='music_project/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='musicians.musicproject')),
            ],
        ),
    ]
