# Generated by Django 5.0.13 on 2025-04-24 00:55

import musicians.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_musicproject_biography_musicproject_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discography',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='musicprojectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path),
        ),
    ]
