# Generated by Django 5.0.13 on 2025-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_alter_discography_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='musicproject',
            name='topics',
            field=models.ManyToManyField(blank=True, to='musicians.topicartist'),
        ),
    ]
