# Generated by Django 5.0.13 on 2025-07-06 06:22

import musicians.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0008_topicartist_musicproject_topics'),
        ('orders', '0019_remove_order_band_remove_order_list_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='core.instrument'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='number_courses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='number_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='orderservices',
            field=models.ManyToManyField(blank=True, to='orders.orderservicetype'),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
