# Generated by Django 5.0.13 on 2025-07-06 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0010_alter_musicproject_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicproject',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.language'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='music_genre_tags',
            field=models.ManyToManyField(blank=True, to='core.musicalgenretag'),
        ),
        migrations.AlterField(
            model_name='musicproject',
            name='topics',
            field=models.ManyToManyField(blank=True, to='musicians.topicartist'),
        ),
    ]
