# Generated by Django 5.0.13 on 2025-07-13 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0011_alter_musicproject_languages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMemberBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('acepted', 'Aceptado'), ('canceled', 'Cancelado'), ('inprocess', 'En proceso')], max_length=20)),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitemusicproject', to='musicians.musicproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_musicproject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
