# Generated by Django 5.0.13 on 2025-07-16 22:47

import musicians.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0012_invitememberband'),
        ('orders', '0020_order_list_musicprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230, unique=True)),
                ('reference', models.CharField(max_length=230)),
                ('image', models.ImageField(upload_to=musicians.utils.dynamic_upload_path)),
                ('instruments', models.ManyToManyField(blank=True, to='core.instrument')),
                ('languages', models.ManyToManyField(blank=True, to='core.language')),
                ('orderservices', models.ManyToManyField(blank=True, to='orders.orderservicetype')),
                ('topics', models.ManyToManyField(blank=True, to='musicians.topicartist')),
            ],
        ),
    ]
