# Generated by Django 5.0.13 on 2025-07-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0013_categorymusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymusic',
            name='music_genre_tags',
            field=models.ManyToManyField(blank=True, to='core.musicalgenretag'),
        ),
    ]
