# Generated by Django 5.0.13 on 2025-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0014_categorymusic_music_genre_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymusic',
            name='typemusictext',
            field=models.CharField(default='Intermedio', max_length=150),
        ),
    ]
