# Generated by Django 5.0.13 on 2025-08-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0015_categorymusic_typemusictext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproject',
            name='instruments',
        ),
        migrations.CreateModel(
            name='MusicProjectInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument')),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musicproject')),
            ],
            options={
                'unique_together': {('music_project', 'instrument')},
            },
        ),
    ]
