# Generated by Django 5.0.13 on 2025-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('musicians', '0016_remove_musicproject_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='instruments',
            field=models.ManyToManyField(blank=True, through='musicians.MusicProjectInstrument', to='core.instrument'),
        ),
    ]
