# Generated by Django 5.0.13 on 2025-08-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0017_musicproject_instruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_set_name', models.CharField(max_length=150)),
                ('instruments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.musicprojectinstrument')),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musicproject')),
            ],
        ),
    ]
