# Generated by Django 5.0.13 on 2025-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0018_instrumentset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentset',
            name='instruments',
        ),
        migrations.AddField(
            model_name='instrumentset',
            name='instruments',
            field=models.ManyToManyField(blank=True, related_name='instrument_set', to='musicians.musicprojectinstrument'),
        ),
    ]
