# Generated by Django 5.0.13 on 2025-08-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0019_remove_instrumentset_instruments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentset',
            name='music_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.musicproject'),
        ),
    ]
