# Generated by Django 5.0.13 on 2025-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0020_alter_instrumentset_music_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
