# Generated by Django 5.0.13 on 2025-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0021_musicproject_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
