# Generated by Django 5.0.13 on 2025-08-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instrumenttype_instrument_type'),
        ('musicians', '0022_musicproject_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
