# Generated by Django 5.0.13 on 2025-08-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0023_musicproject_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='single',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='singles', to='musicians.discography'),
        ),
    ]
