# Generated by Django 5.0.13 on 2025-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0024_single_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='isAvailabilityCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='isProfileInfoCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='isVerificationStepsCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
