# Generated by Django 5.0.13 on 2025-08-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0025_musicproject_isavailabilitycompleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitememberband',
            name='user',
        ),
        migrations.AddField(
            model_name='invitememberband',
            name='invited_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invited_musicproject', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitememberband',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviter_musicproject', to=settings.AUTH_USER_MODEL),
        ),
    ]
