# Generated by Django 5.0.13 on 2025-08-20 17:41

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0027_invitememberband_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitememberband',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 27, 17, 41, 43, 524187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='invitememberband',
            name='responded_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invitememberband',
            unique_together={('music_project', 'email', 'status')},
        ),
        migrations.AddIndex(
            model_name='invitememberband',
            index=models.Index(fields=['email', 'status'], name='musicians_i_email_354d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='invitememberband',
            index=models.Index(fields=['expires_at'], name='musicians_i_expires_f49e48_idx'),
        ),
    ]
