# Generated by Django 5.0.13 on 2025-08-20 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0028_invitememberband_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitememberband',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invitememberband',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitememberband',
            name='status',
            field=models.CharField(choices=[('acepted', 'Aceptado'), ('canceled', 'Cancelado'), ('inprocess', 'En proceso')], default='inprocess', max_length=20),
        ),
    ]
