# Generated by Django 5.0.13 on 2025-08-21 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0029_alter_invitememberband_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentset',
            name='instruments',
        ),
        migrations.AddField(
            model_name='musicprojectinstrument',
            name='price_per_instrument',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instrumentset',
            name='music_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_sets', to='musicians.musicproject'),
        ),
        migrations.CreateModel(
            name='MusicProjectInstrumentInstrumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_for_set', models.PositiveIntegerField(default=1)),
                ('instrument_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.instrumentset')),
                ('music_project_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.musicprojectinstrument')),
            ],
            options={
                'unique_together': {('music_project_instrument', 'instrument_set')},
            },
        ),
        migrations.AddField(
            model_name='instrumentset',
            name='instruments_in_current_set',
            field=models.ManyToManyField(blank=True, related_name='instrument_set', through='musicians.MusicProjectInstrumentInstrumentSet', to='musicians.musicprojectinstrument'),
        ),
    ]
