# Generated by Django 5.0.13 on 2025-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0030_remove_instrumentset_instruments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='categories',
            field=models.ManyToManyField(blank=True, to='musicians.categorymusic'),
        ),
    ]
