# Generated by Django 5.0.13 on 2025-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0031_musicproject_categories'),
        ('services', '0004_category_image_item_image_specificservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='musicprojects', to='services.category'),
        ),
    ]
