# Generated by Django 5.0.13 on 2025-09-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0032_musicproject_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitememberband',
            name='status',
            field=models.CharField(choices=[('accepted', 'Aceptado'), ('canceled', 'Cancelado'), ('in_process', 'En proceso')], default='inprocess', max_length=20),
        ),
    ]
