# Generated by Django 5.0.13 on 2025-09-05 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0034_alter_invitememberband_status'),
        ('services', '0005_pricinginterval_remove_attribute_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='musicprojectservice',
            name='attribute',
        ),
    ]
