# Generated by Django 5.0.13 on 2025-09-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0035_alter_musicprojectservice_unique_together_and_more'),
        ('services', '0007_category_id_item_id_specificservice_id_and_more'),
    ]

    operations = [
    ]
