# Generated by Django 5.0.13 on 2025-09-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0037_delete_unique_constraint'),
    ]

    operations = [
    ]
