# Generated by Django 5.0.13 on 2025-09-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0038_alter_musicprojectservice_unique_together'),
        ('services', '0007_category_id_item_id_specificservice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectservice',
            name='category',
            field=models.ForeignKey(default='MUSIC_LEARNING', on_delete=django.db.models.deletion.CASCADE, to='services.category', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='item',
            field=models.ForeignKey(default='desarrollo-aprendizaje-instrumentos-canto', on_delete=django.db.models.deletion.CASCADE, to='services.item', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='pricing_intervals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.pricinginterval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='specific_service',
            field=models.ForeignKey(default='instrumento-musical', on_delete=django.db.models.deletion.CASCADE, related_name='musicprojects', to='services.specificservice', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='title',
            field=models.CharField(default='Nuevo Servicio', max_length=200),
            preserve_default=False,
        ),
    ]
