# Generated by Django 5.0.13 on 2025-09-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0039_musicprojectservice_category_and_more'),
        ('services', '0007_category_id_item_id_specificservice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectservice',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.attribute'),
        ),
    ]
