# Generated by Django 5.0.13 on 2025-09-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0040_alter_musicprojectservice_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicprojectservice',
            unique_together=set(),
        ),
    ]
