# Generated by Django 5.0.13 on 2025-09-06 23:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0041_alter_musicprojectservice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='selected_instrument_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.musicprojectinstrumentinstrumentset'),
        ),
        migrations.AddField(
            model_name='musicprojectservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
