# Generated by Django 5.0.13 on 2025-09-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0042_musicprojectservice_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicprojectservice',
            name='pricing_intervals',
        ),
    ]
