# Generated by Django 5.0.13 on 2025-09-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0043_remove_musicprojectservice_pricing_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymusic',
            name='type_input',
            field=models.CharField(choices=[('select', 'Selección única'), ('multiple', 'Selección multiple')], default='select', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topicartist',
            name='individual',
            field=models.BooleanField(default=False),
        ),
    ]
