# Generated by Django 5.0.13 on 2025-09-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0043_remove_musicprojectservice_pricing_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityInfoDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityInfoTimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_info', to='musicians.musicproject')),
                ('day_schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.availabilityinfodayschedule')),
                ('time_schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.availabilityinfotimeschedule')),
            ],
            options={
                'unique_together': {('music_project', 'day_schedule', 'time_schedule')},
            },
        ),
    ]
