# Generated by Django 5.0.13 on 2025-09-10 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0044_availabilityinfodayschedule_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilityinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availabilityinfodayschedule',
            name='availability_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='day_schedule', to='musicians.availabilityinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilityinfotimeschedule',
            name='availability_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='time_schedule', to='musicians.availabilityinfo'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='availabilityinfo',
            name='day_schedule',
        ),
        migrations.RemoveField(
            model_name='availabilityinfo',
            name='time_schedule',
        ),
    ]
