# Generated by Django 5.0.13 on 2025-09-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0044_categorymusic_type_input_topicartist_individual'),
        ('services', '0017_alter_item_category_alter_specificservice_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymusic',
            name='type_musician',
            field=models.CharField(choices=[('vocalist', 'Vocalistas'), ('instrumentalist', 'Instrumetalista'), ('multiinstrumentalist', 'Multi Instrumetalista'), ('djproductor', 'DJ Productor')], default='select', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='musicprojectservice',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.item', to_field='name'),
        ),
    ]
