# Generated by Django 5.0.13 on 2025-09-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0045_alter_availabilityinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabilityinfodayschedule',
            old_name='availability_id',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='availabilityinfotimeschedule',
            old_name='availability_id',
            new_name='availability',
        ),
    ]
