# Generated by Django 5.0.13 on 2025-09-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0046_rename_availability_id_availabilityinfodayschedule_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityinfo',
            name='music_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_info', to='musicians.musicproject'),
        ),
    ]
