# Generated by Django 5.0.13 on 2025-09-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0047_alter_availabilityinfo_music_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproject',
            name='availability_for',
        ),
        migrations.AddField(
            model_name='availabilityinfodayschedule',
            name='modality',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('on_site', 'On Site')], default='on_site', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabilityinfotimeschedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10),
        ),
    ]
