# Generated by Django 5.0.13 on 2025-09-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0045_categorymusic_type_musician_and_more'),
        ('musicians', '0048_remove_musicproject_availability_for_and_more'),
    ]

    operations = [
    ]
