# Generated by Django 5.0.13 on 2025-10-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0050_musicprojectvideo_musicprojectvideodraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprojectvideodraft',
            name='status',
            field=models.CharField(choices=[('INPROCESS', 'inprocess'), ('ACCEPTED', 'accepted'), ('REJECTED', 'rejected')], default='INPROCESS', max_length=100),
        ),
    ]
