# Generated by Django 5.0.13 on 2025-10-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0051_alter_musicprojectvideodraft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectinstrument',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musicprojectinstrument',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
