# Generated by Django 5.0.13 on 2025-10-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0052_musicprojectinstrument_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
