# Generated by Django 5.0.13 on 2025-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0053_musicproject_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
