# Generated by Django 5.0.13 on 2025-11-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0054_musicproject_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicproject',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='musicproject',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
