# Generated by Django 5.0.13 on 2025-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0055_remove_musicproject_deleted_at_musicproject_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprojectimage',
            name='thumbnail_position',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
