# Generated by Django 5.0.13 on 2025-12-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0056_musicprojectimage_thumbnail_position'),
        ('orders', '0026_alter_order_list_musicprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='feedback_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('music_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='musicians.musicproject')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='orders.order')),
            ],
        ),
    ]
