# Generated by Django 5.0.13 on 2025-12-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0057_musicproject_feedback_count_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicproject',
            name='isInstrumentsCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='musicproject',
            name='isServicesCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
