# Generated by Django 5.0.13 on 2025-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0058_musicproject_isinstrumentscompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discography',
            name='year_of_release',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
