# Generated by Django 5.0.13 on 2025-12-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0059_discography_year_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discography',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discography',
            name='url_link',
            field=models.URLField(),
        ),
    ]
