# Generated by Django 5.0.13 on 2025-12-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0060_alter_discography_title_alter_discography_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discography',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
