# Generated by Django 5.0.13 on 2025-12-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0061_alter_discography_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprojectservice',
            name='selected_instrument_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.instrumentset'),
        ),
    ]
