# Generated by Django 5.0.13 on 2025-12-18 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0062_alter_musicprojectservice_selected_instrument_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitememberband',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
