# Generated by Django 5.0.13 on 2025-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_customization_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificservice',
            name='extra_fields',
            field=models.JSONField(default=dict),
        ),
    ]
