# Generated by Django 5.0.13 on 2025-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_attribute_is_customization_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificservice',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
