# Generated by Django 5.0.13 on 2025-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_specificservice_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/categories/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/items/'),
        ),
        migrations.AddField(
            model_name='specificservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/specific_services/'),
        ),
    ]
