# Generated by Django 5.0.13 on 2025-09-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category_image_item_image_specificservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_class',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_customization_allowed',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='specificservice',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='specificservice',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='specificservice',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
