# Generated by Django 5.0.13 on 2025-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_pricinginterval_remove_attribute_currency_and_more'),
    ]

    operations = [
    ]
