# Generated by Django 5.0.13 on 2025-09-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_attribute_id_alter_category_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinginterval',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
