# Generated by Django 5.0.13 on 2025-09-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0043_remove_musicprojectservice_pricing_intervals'),
        ('services', '0009_pricinginterval_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinginterval',
            name='music_project_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_intervals', to='musicians.musicprojectservice'),
        ),
    ]
