# Generated by Django 5.0.13 on 2025-09-09 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_pricinginterval_music_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category', to_field='name'),
        ),
        migrations.AddField(
            model_name='specificservice',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='specificservice',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_services', to='services.item', to_field='name'),
        ),
    ]
