# Generated by Django 5.0.13 on 2025-09-09 02:05

from django.db import migrations

def populate_item_id(apps, schema_editor):
    Item = apps.get_model('services', 'Item')
    Category = apps.get_model('services', 'Category')

    for item in Item.objects.all():

        if item.category:
            item.category_name = Category.objects.get(name=item.category.name)

        item.save()

def populate_specific_service_id(apps, schema_editor):
    SpecificService = apps.get_model('services', 'SpecificService')
    Item = apps.get_model('services', 'Item')

    for specific_service in SpecificService.objects.all():

        if specific_service.item:
            specific_service.item_name = Item.objects.get(name=specific_service.item.name)

        specific_service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_item_category_name_specificservice_extra_fields_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_item_id, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_specific_service_id, reverse_code=migrations.RunPython.noop),
    ]
