# Generated by Django 5.0.13 on 2025-09-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_auto_20250909_0222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="specificservice",
            name="item",
        ),

        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="services.category",
                null=True,
                blank=True
            ),
        ),
        migrations.AddField(
            model_name="specificservice",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.item",
                null=True,
                blank=True
            ),
        ),
    ]
