# Generated by Django 5.0.13 on 2025-09-09 02:38
from django.db import migrations

def populate_item_id(apps, schema_editor):
    Item = apps.get_model('services', 'Item')
    Category = apps.get_model('services', 'Category')

    for item in Item.objects.all():

        if item.category:
            item.category = Category.objects.get(name=item.category_name)

        item.save()

def populate_specific_service_id(apps, schema_editor):
    SpecificService = apps.get_model('services', 'SpecificService')
    Item = apps.get_model('services', 'Item')

    for specific_service in SpecificService.objects.all():

        if specific_service.item:
            specific_service.item = Item.objects.get(name=specific_service.item_name)

        specific_service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_item_category_alter_specificservice_item'),
    ]

    operations = [
    ]
