# Generated by Django 5.0.13 on 2025-09-09 02:50

from django.db import migrations


def populate_item_id(apps, schema_editor):
    Item = apps.get_model("services", "Item")
    Category = apps.get_model("services", "Category")

    for item in Item.objects.all():

        if item.category_name:
            item.category = Category.objects.get(name=item.category_name.name)

        item.save()


def populate_specific_service_id(apps, schema_editor):
    SpecificService = apps.get_model("services", "SpecificService")
    Item = apps.get_model("services", "Item")

    for specific_service in SpecificService.objects.all():

        if specific_service.item_name:
            specific_service.item = Item.objects.get(name=specific_service.item_name.name)

        specific_service.save()


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_auto_20250909_0244"),
    ]

    operations = [
        migrations.RunPython(populate_item_id, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_specific_service_id, reverse_code=migrations.RunPython.noop),
    ]
