# Generated by Django 5.0.13 on 2025-09-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20250909_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specificservice',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.item'),
            preserve_default=False,
        ),
    ]
