# Generated by Django 5.0.13 on 2025-03-21 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboardingdifficulty',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_difficulties', to='roles.role'),
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='clients.clienttype'),
        ),
        migrations.AddField(
            model_name='userprofileonboardingdifficulty',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientonboardingdifficulty'),
        ),
        migrations.AddField(
            model_name='userprofileonboardingdifficulty',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_onboarding_difficulties', to='roles.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofileonboardingdifficulty',
            unique_together={('user_profile', 'difficulty')},
        ),
    ]
