# Generated by Django 5.0.13 on 2025-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/client_detail/'),
        ),
        migrations.AddField(
            model_name='clienttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/client_types/'),
        ),
    ]
