# Generated by Django 5.0.13 on 2025-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientdetail_image_clienttype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientonboardingdifficulty',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
