# Generated by Django 5.0.13 on 2025-12-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientdetail_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
