# Generated by Django 5.0.13 on 2025-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientdetail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboardingdifficulty',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
