# Generated by Django 5.0.13 on 2025-04-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roles/'),
        ),
    ]
