# Generated by Django 5.0.13 on 2025-06-30 23:30

import django.db.models.deletion
import musicians.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('orders', '0018_order_band_order_status'),
        ('roles', '0003_userprofile_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path)),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('number_students', models.IntegerField(blank=True, default=0, null=True)),
                ('number_courses', models.IntegerField(blank=True, default=0, null=True)),
                ('year_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('instruments', models.ManyToManyField(blank=True, to='core.instrument')),
                ('languages', models.ManyToManyField(blank=True, to='core.language')),
                ('musical_genre_tag', models.ManyToManyField(blank=True, to='core.musicalgenretag')),
                ('order_services', models.ManyToManyField(blank=True, to='orders.orderservicetype')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilebasic', to='roles.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofileartist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('type', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('SPOTIFY', 'Spotify'), ('OTHER', 'Otro')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=musicians.utils.dynamic_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileArtistAdmin',
            fields=[
                ('userprofileartist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.userprofileartist')),
            ],
            bases=('roles.userprofileartist',),
        ),
    ]
