# Generated by Django 5.0.13 on 2025-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_userprofileartist_album_gallery_and_more'),
        ('services', '0004_category_image_item_image_specificservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofileartist',
            name='items',
            field=models.ManyToManyField(blank=True, to='services.item'),
        ),
        migrations.AddField(
            model_name='userprofileartist',
            name='topics',
            field=models.ManyToManyField(blank=True, to='roles.topicartist'),
        ),
    ]
