# Generated by Django 5.0.13 on 2025-07-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_topicartist_userprofileartist_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileartist',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='musical_genre_tag',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='order_services',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofileartist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofileartistadmin',
            name='userprofileartist_ptr',
        ),
        migrations.DeleteModel(
            name='TopicArtist',
        ),
        migrations.DeleteModel(
            name='UserProfileArtist',
        ),
        migrations.DeleteModel(
            name='UserProfileArtistAdmin',
        ),
    ]
