# Generated by Django 5.0.13 on 2025-08-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_instrumenttype_instrument_type'),
        ('roles', '0006_remove_userprofileartist_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='core.language'),
        ),
    ]
