# Generated by Django 5.0.13 on 2025-08-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_remove_userprofile_languages_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
