# Generated by Django 5.0.13 on 2025-09-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0010_alter_userprofile_language'),
        ('services', '0017_alter_item_category_alter_specificservice_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demografy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('other', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeyDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('other', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.category'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contracting_modalty',
            field=models.CharField(blank=True, choices=[('ones', 'One-off (único evento)'), ('mensual_supscription', 'Suscripción mensual'), ('quarterly', 'Paquete trimestrales'), ('annual', 'Paquetes anuales')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='frecuency',
            field=models.CharField(blank=True, choices=[('ones', 'One-off (único evento)'), ('mensual_supscription', 'Suscripción mensual'), ('quarterly', 'Paquete trimestrales'), ('annual', 'Paquetes anuales')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='services.item'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='KeyDatesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_other', models.BooleanField(default=False)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('key_dates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keydatesprofile', to='roles.keydates')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ListDemografyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_other', models.BooleanField(default=False)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('demografy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demografyprofile', to='roles.demografy')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.userprofile')),
            ],
        ),
    ]
