# Generated by Django 5.0.13 on 2025-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='frecuency',
            field=models.CharField(blank=True, choices=[('ones', 'Unico (one-shot)'), ('mensual', 'Mensual'), ('quarterly', 'Trimestral'), ('biannual', 'Semestral'), ('annual', 'Anual')], max_length=255, null=True),
        ),
    ]
