# Generated by Django 5.0.13 on 2025-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_alter_userprofile_frecuency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=255, null=True),
        ),
    ]
