# Generated by Django 5.0.13 on 2025-10-17 19:16

import roles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_userprofile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=255, null=True, validators=[roles.models.validate_timezone]),
        ),
    ]
