# Generated by Django 5.0.13 on 2025-12-17 00:19

import django.db.models.deletion
import utils.get_default_language
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_notification_value_notification_redirect_link_and_more'),
        ('roles', '0016_alter_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(default=utils.get_default_language.get_default_language, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.language'),
        ),
    ]
