# Generated by Django 5.0.13 on 2025-03-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_collabtype_djtype_equipment_instrument_and_more'),
        ('roles', '0001_initial'),
        ('services', '0002_attribute_is_customization_allowed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_custom_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('visited', 'Visited')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MusicAmbianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allow_custom_message', models.BooleanField(default=False)),
                ('customer_lifecycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerlifecycle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_custom_message', models.TextField(blank=True, null=True)),
                ('event_goal_custom_message', models.TextField(blank=True, null=True)),
                ('has_specific_requirements', models.BooleanField(default=False)),
                ('specific_requirements', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('event_city', models.TextField(blank=True, null=True)),
                ('event_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('venue_type', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10, null=True)),
                ('sound_setup', models.CharField(blank=True, choices=[('own_equipment', 'Owned Equipment'), ('musician_provided_equipment', 'Musician Provided Equipment'), ('advice_needed', 'Advice Needed')], max_length=50, null=True)),
                ('estimated_capacity', models.CharField(blank=True, choices=[('Less_than_50', 'Less than 50'), ('50_and_100', 'Between 50 and 100'), ('100_and_300', 'Between 100 and 300'), ('300_and_500', 'Between 300 and 500'), ('more_than_500', 'More than 500')], max_length=20, null=True)),
                ('sound_restriction', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('event_duration', models.CharField(choices=[('one_hour', 'less than 1 Hour'), ('one_and_two_hours', '1 - 2 Hours'), ('three_and_four_hours', '3 - 4 Hours'), ('custom', 'More than 4 Hours')], max_length=20)),
                ('custom_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('ambiance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.musicambiancetype')),
                ('collab_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collabtype')),
                ('event_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.eventgoal')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.eventtype')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.item')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicemode')),
                ('music_genre_tags', models.ManyToManyField(blank=True, to='core.musicalgenretag')),
                ('referral_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.referralsource')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='roles.userprofile')),
                ('visits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.eventvisit')),
                ('sound_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.soundpackage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.attribute')),
                ('dj_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.djtype')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instrument')),
                ('musician_voice_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.musicianvoicetype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('specific_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.specificservice')),
                ('vocal_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vocalstyle')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'unique_together': {('order', 'equipment')},
            },
        ),
    ]
