# Generated by Django 5.0.13 on 2025-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collabtype_djtype_equipment_instrument_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='instrument',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='core.instrument'),
        ),
    ]
