# Generated by Django 5.0.13 on 2025-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_instrument_orderitem_instruments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='visits',
            new_name='visit',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
