# Generated by Django 5.0.13 on 2025-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderservicetype_alter_order_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
    ]
