# Generated by Django 5.0.13 on 2025-04-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_latitude_alter_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/event_types/'),
        ),
        migrations.AddField(
            model_name='musicambiancetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/music_ambiance_type/'),
        ),
    ]
