# Generated by Django 5.0.13 on 2025-04-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_eventtype_image_musicambiancetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/service_types/'),
        ),
    ]
