# Generated by Django 5.0.13 on 2025-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderservicetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
