# Generated by Django 5.0.13 on 2025-04-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_max_budget_order_min_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_capacity',
            field=models.CharField(blank=True, choices=[('Less_than_50', 'Menos de 50'), ('50_and_100', 'Entre 50 y 100'), ('100_and_300', 'Entre 100 y 300'), ('300_and_500', 'Entre 300 y 500'), ('more_than_500', 'Más de 500')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='event_duration',
            field=models.CharField(choices=[('one_hour', 'Menos de una hora'), ('one_and_two_hours', '1 - 2 horas'), ('three_and_four_hours', '3 - 4 horas'), ('custom', 'Más de 4 horas')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='sound_setup',
            field=models.CharField(blank=True, choices=[('own_equipment', 'Equipo propio'), ('musician_provided_equipment', 'Profesional lleva su propio equipo'), ('advice_needed', 'Requerimos asesoría')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('indoor', 'Espacio cerrado'), ('outdoor', 'Al aire libre')], max_length=10, null=True),
        ),
    ]
