# Generated by Django 5.0.13 on 2025-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_estimated_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgoal',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderservicetype',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
