# Generated by Django 5.0.13 on 2025-04-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_eventgoal_sequence_orderservicetype_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderservicetype',
            name='sequence',
        ),
    ]
