# Generated by Django 5.0.13 on 2025-04-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_orderservicetype_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
