# Generated by Django 5.0.13 on 2025-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_eventtype_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='path',
            field=models.CharField(blank=True, choices=[('blank', 'En blanco'), ('artist', 'Seleccionando artista'), ('template', 'Por plantilla'), ('band', 'Banda')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='profile_beneficiary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
