# Generated by Django 5.0.13 on 2025-06-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('orders', '0015_order_estimated_age_order_path_and_more'),
        ('services', '0004_category_image_item_image_specificservice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('idea', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/order_template/')),
                ('technical_level', models.CharField(blank=True, choices=[('medium', 'Medio'), ('proffesional', 'Profesional')], max_length=60, null=True)),
                ('logistics', models.BooleanField(default=False)),
                ('personalization', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('featured_tag', models.CharField(blank=True, choices=[('popular', 'Popular'), ('new', 'Nuevo'), ('promotion', 'En promoción'), ('recommended', 'Recomendado'), ('top', 'Top local')], max_length=60, null=True)),
                ('cta_label_1', models.CharField(blank=True, null=True)),
                ('cta_label_2', models.CharField(blank=True, null=True)),
                ('ambiance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.musicambiancetype')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.eventtype')),
                ('instruments', models.ManyToManyField(blank=True, to='core.instrument')),
                ('modality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicemode')),
                ('music_genre_tags', models.ManyToManyField(blank=True, to='core.musicalgenretag')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ordertemplate'),
        ),
    ]
