# Generated by Django 5.0.13 on 2025-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_ordertemplate_order_order_template'),
        ('roles', '0002_role_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_artist',
            field=models.ManyToManyField(blank=True, to='roles.userprofile'),
        ),
    ]
