# Generated by Django 5.0.13 on 2025-06-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0007_alter_discography_cover_image_and_more'),
        ('orders', '0017_order_list_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicians.musicproject'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CONCEPT_DEFINED', 'Cliente definio concepto'), ('MUSICIANS_SELECTED', 'Musico seleccionado'), ('SCOUTING_INITIATED', 'Inicio acounting en el lugar'), ('LOGISTICS_PROPOSAL_SENT', 'Envio de propuesta de lógistica'), ('LOGISTICS_PROPOSAL_ACCEPTED', 'Cliente acepto la propuesta de logistica'), ('LOGISTICS_PROPOSAL_REJECTED', 'Cliente rechazo la propuesta de logistica'), ('ORDER_CONFIRMED', 'Cliente confirmo la orden'), ('CHECKLIST_IN_PROGRESS', 'Orden en proceso'), ('EVENT_EXECUTING', 'Evento siendo ejecutado'), ('ORDER_COMPLETED', 'Orden completado'), ('ORDER_CANCELLED', 'Orden cancelado'), ('POST_EVENT_FEEDBACK_PENDING', 'Pendiente de recibir feedback'), ('POST_EVENT_FEEDBACK_RECEIVED', 'Feedback recibido')], max_length=100, null=True),
        ),
    ]
