# Generated by Django 5.0.13 on 2025-07-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0008_topicartist_musicproject_topics'),
        ('orders', '0018_order_band_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='band',
        ),
        migrations.RemoveField(
            model_name='order',
            name='list_artist',
        ),
    ]
