# Generated by Django 5.0.13 on 2025-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0011_alter_musicproject_languages_and_more'),
        ('orders', '0019_remove_order_band_remove_order_list_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_musicprojects',
            field=models.ManyToManyField(blank=True, to='musicians.musicproject'),
        ),
    ]
