# Generated by Django 5.0.13 on 2025-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0015_categorymusic_typemusictext'),
        ('orders', '0020_order_list_musicprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='categories_music',
            field=models.ManyToManyField(blank=True, to='musicians.categorymusic'),
        ),
    ]
