# Generated by Django 5.0.13 on 2025-07-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gender_sequence'),
        ('orders', '0021_order_categories_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list_equipment',
            field=models.ManyToManyField(blank=True, to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='path',
            field=models.CharField(blank=True, choices=[('blank', 'En blanco'), ('artist', 'Seleccionando artista'), ('template', 'Por plantilla'), ('band', 'Banda'), ('soundequipment', 'Equipo de Sonido')], max_length=100, null=True),
        ),
    ]
