# Generated by Django 5.0.13 on 2025-08-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_list_equipment_alter_order_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(blank=True, choices=[('blank', 'En blanco'), ('artist', 'Seleccionando artista'), ('template', 'Por plantilla'), ('band', 'Banda'), ('soundequipment', 'Equipo de Sonido')], max_length=100, null=True),
        ),
    ]
