# Generated by Django 5.0.13 on 2025-08-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ideas_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
