# Generated by Django 5.0.13 on 2025-09-10 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0045_categorymusic_type_musician_and_more'),
        ('orders', '0024_order_ideas_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicians.categorymusic'),
        ),
    ]
