# Generated by Django 5.0.13 on 2025-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0056_musicprojectimage_thumbnail_position'),
        ('orders', '0025_orderitem_category_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='list_musicprojects',
            field=models.ManyToManyField(blank=True, related_name='orders', to='musicians.musicproject'),
        ),
    ]
